export const EMAIL_CHANGE = 'EMAIL_CHANGE';
export const PASSWORD_CHANGE = 'PASSWORD_CHANGE';
export const LOG_IN = 'LOG_IN';
export const LOG_IN_FAIL = 'LOG_IN_FAIL';
export const LOG_IN_USER = 'LOG_IN_USER';

export const EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE';
export const EMPLOYEE_CREATE = 'EMPLOYEE_CREATE';
export const EMPLOYEE_FETCH = 'EMPLOYEE_FETCH';
export const EMPLOYEE_EDT_SAVE = 'EMPLOYEE_EDT_SAVE';
export const EMPLOYEE_DELETE = 'EMPLOYEE_DELETE';